# Copyright 2024 Jonathan Amsterdam. All rights reserved.
# Use of this source code is governed by a license that can be found in the LICENSE
# file.

trailingComma: 'es5'
semi: true
singleQuote: true
bracketSameLine: true
